//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISCOAEntities : DbContext
    {
        public SISCOAEntities()
            : base("name=SISCOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TSISCOA_Control> TSISCOA_Control { get; set; }
        public virtual DbSet<TSISCOA_Estado> TSISCOA_Estado { get; set; }
        public virtual DbSet<TSISCOA_Periodo> TSISCOA_Periodo { get; set; }
        public virtual DbSet<TSISCOA_Oficina> TSISCOA_Oficina { get; set; }
        public virtual DbSet<TSISCOA_OficinaControl> TSISCOA_OficinaControl { get; set; }
        public virtual DbSet<TSISCOA_Permiso> TSISCOA_Permiso { get; set; }
        public virtual DbSet<TSISCOA_Rol> TSISCOA_Rol { get; set; }
        public virtual DbSet<TSISCOA_RolPermiso> TSISCOA_RolPermiso { get; set; }
        public virtual DbSet<TSISCOA_Usuario> TSISCOA_Usuario { get; set; }
    }
}
