--CREATE DATABASE SISCOA

USE SISCOA

--CREATE SCHEMA CONTROL;
--CREATE SCHEMA OFICINA;
--CREATE SCHEMA USUARIO;



/**
DROP TABLE [USUARIO].[TSISCOA_Usuario]
DROP TABLE [USUARIO].[TSISCOA_RolPermiso]
DROP TABLE [USUARIO].[TSISCOA_Rol]
DROP TABLE [USUARIO].[TSISCOA_Permiso]
DROP TABLE [OFICINA].[TSISCOA_OficinaControl]
DROP TABLE [OFICINA].[TSISCOA_Oficina]
DROP TABLE [CONTROL].[TSISCOA_Control]
DROP TABLE [CONTROL].[TSISCOA_Periodo]
DROP TABLE [CONTROL].[TSISCOA_Estado]
**/


CREATE TABLE CONTROL.TSISCOA_Estado
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL
)
 
CREATE TABLE CONTROL.TSISCOA_Periodo
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TF_FechaInicio DATE,
	TF_FechaFin DATE,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL
)

CREATE TABLE CONTROL.TSISCOA_Control
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TC_DescriptionDocumentacionEvidencia VARCHAR(255) NOT NULL,
	FK_TN_Estado INT NULL,
	FK_TN_Periodo INT NULL,
	TB_NotificacionCorreoAColaborador BIT NOT NULL DEFAULT 0,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL,
	FOREIGN KEY (FK_TN_Estado) REFERENCES [CONTROL].[TSISCOA_Estado](ID),
	FOREIGN KEY (FK_TN_Periodo) REFERENCES [CONTROL].[TSISCOA_Periodo](ID)
)

CREATE TABLE OFICINA.TSISCOA_Oficina
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_CodigoOficina VARCHAR(25) NULL,
	TC_Nombre VARCHAR(50) NOT NULL,
	TC_Institucion VARCHAR(50) NULL,
	TB_EstadoActividad BIT NOT NULL DEFAULT 0,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL
)

CREATE TABLE OFICINA.TSISCOA_OficinaControl
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FK_SISCOA_CONTROL_SISCOA_OficinaControl INT NOT NULL,
	FK_SISCOA_OFICINA_SISCOA_OficinaControl INT NOT NULL,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL,
	FOREIGN KEY (FK_SISCOA_CONTROL_SISCOA_OficinaControl) REFERENCES [CONTROL].[TSISCOA_Control](ID),
	FOREIGN KEY (FK_SISCOA_OFICINA_SISCOA_OficinaControl) REFERENCES [OFICINA].[TSISCOA_Oficina](ID)
)

CREATE TABLE USUARIO.TSISCOA_Permiso
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL
)

CREATE TABLE USUARIO.TSISCOA_Rol
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL
)

CREATE TABLE USUARIO.TSISCOA_RolPermiso
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FK_SISCOA_Rol_SISCOA_RolPermiso INT NOT NULL,
	FK_SISCOA_Permiso_SISCOA_RolPermiso INT NOT NULL,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL,
	FOREIGN KEY (FK_SISCOA_Rol_SISCOA_RolPermiso) REFERENCES [USUARIO].[TSISCOA_Rol](ID),
	FOREIGN KEY (FK_SISCOA_Permiso_SISCOA_RolPermiso) REFERENCES [USUARIO].[TSISCOA_Permiso](ID)
)

CREATE TABLE USUARIO.TSISCOA_Usuario
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TC_PrimerApellido VARCHAR(50) NOT NULL,
	TC_SegundoApellido VARCHAR(50) NOT NULL,
	TV_Contrasenna VARBINARY(255) NOT NULL,
	TC_Correo VARCHAR(50) NOT NULL,
	FK_SISCOA_Oficina_SISCOA_Usuario INT NOT NULL,
	FK_SISCOA_Rol_SISCOA_Usuario INT NOT NULL,
	TB_EstaActivo BIT DEFAULT 1,
	TB_EstaBorrado BIT DEFAULT 0,
	TC_UltimaModificacion VARCHAR(50) DEFAULT SUSER_NAME() NOT NULL,
	TF_UltimaFechaModificacion DATETIME DEFAULT GETDATE() NOT NULL,
	FOREIGN KEY (FK_SISCOA_Oficina_SISCOA_Usuario) REFERENCES [OFICINA].[TSISCOA_Oficina](ID),
	FOREIGN KEY (FK_SISCOA_Rol_SISCOA_Usuario) REFERENCES [USUARIO].[TSISCOA_Rol](ID)
)


