

USE SISCOA


CREATE TABLE CONTROL.TSISCOA_Estado
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL
)
 
CREATE TABLE CONTROL.TSISCOA_Periodo
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TF_FechaInicio DATETIME,
	TF_FechaFin DATETIME
)

CREATE TABLE CONTROL.TSISCOA_Control
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL,
	TC_DescriptionDocumentacionEvidencia VARCHAR(255) NOT NULL,
	TB_NotificacionCorreoAColaborador BIT NOT NULL DEFAULT 0
)

CREATE TABLE OFICINA.TSISCOA_Oficina
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_CodigoOficina VARCHAR(25) NULL,
	TC_Nombre VARCHAR(50) NOT NULL,
	TC_Institucion VARCHAR(50) NULL,
	TB_EstadoActividad BIT NOT NULL DEFAULT 0
)

CREATE TABLE USUARIO.TSISCOA_Permiso
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL
)

CREATE TABLE USUARIO.TSISCOA_Rol
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(50) NOT NULL
)

CREATE TABLE USUARIO.TSISCOA_RolPermiso
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FK_SISCOA_Rol_SISCOA_RolPermiso INT NOT NULL,
	FK_SISCOA_Permiso_SISCOA_RolPermiso INT NOT NULL,
	FOREIGN KEY (FK_SISCOA_Rol_SISCOA_RolPermiso) REFERENCES [USUARIO].[TSISCOA_Rol](ID),
	FOREIGN KEY (FK_SISCOA_Permiso_SISCOA_RolPermiso) REFERENCES [USUARIO].[TSISCOA_Permiso](ID)
)

CREATE TABLE USUARIO.TSISCOA_Usuario
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Identificacion VARCHAR(50) NOT NULL,
	TC_Nombre VARCHAR(50) NOT NULL,
	TC_PrimerApellido VARCHAR(50) NOT NULL,
	TC_SegundoApellido VARCHAR(50) NOT NULL,
	TV_Contrasenna VARCHAR(256) NOT NULL,
	TC_Correo VARCHAR(50) NOT NULL,
	FK_SISCOA_Oficina_SISCOA_Usuario INT NOT NULL,
	FK_SISCOA_Rol_SISCOA_Usuario INT NOT NULL,
	FOREIGN KEY (FK_SISCOA_Oficina_SISCOA_Usuario) REFERENCES [OFICINA].[TSISCOA_Oficina](ID),
	FOREIGN KEY (FK_SISCOA_Rol_SISCOA_Usuario) REFERENCES [USUARIO].[TSISCOA_Rol](ID)
)

CREATE TABLE SISTEMA.TSISCOA_Error
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Description VARCHAR(512),
	TC_UltimaAccion VARCHAR(100),
	FK_ID_UsuarioActivo INT NOT NULL,
	TF_FechaError DATETIME DEFAULT GETDATE() NOT NULL,
	FOREIGN KEY (FK_ID_UsuarioActivo) REFERENCES [USUARIO].[TSISCOA_Usuario](ID)
)

CREATE TABLE SISTEMA.TSISCOA_Actividad
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Description VARCHAR(255),
	TC_Accion VARCHAR(100),
	FK_ID_UsuarioActivo INT NOT NULL,
	TF_FechaAccion DATETIME DEFAULT GETDATE() NOT NULL,
	FOREIGN KEY (FK_ID_UsuarioActivo) REFERENCES [USUARIO].[TSISCOA_Usuario](ID)
)

CREATE TABLE CONTROL.TSISCOA_OficinaControl
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Comentario VARCHAR(255),
	FK_TN_CONTROL_SISCOA_OficinaControl INT,
	FK_TN_OFICINA_SISCOA_OficinaControl INT,
	FK_TN_ESTADO_SISCOA_OficinaControl INT,
	FK_TN_PERIODO_SISCOA_OficinaControl INT,
	TF_FechaFin_DiasExtra DATE DEFAULT '0001-01-01',
	FOREIGN KEY (FK_TN_CONTROL_SISCOA_OficinaControl) REFERENCES [CONTROL].[TSISCOA_Control](ID),
	FOREIGN KEY (FK_TN_OFICINA_SISCOA_OficinaControl) REFERENCES [OFICINA].[TSISCOA_Oficina](ID),
	FOREIGN KEY (FK_TN_ESTADO_SISCOA_OficinaControl) REFERENCES [CONTROL].[TSISCOA_Estado](ID),
	FOREIGN KEY (FK_TN_PERIODO_SISCOA_OficinaControl) REFERENCES [CONTROL].[TSISCOA_Periodo](ID)
)

CREATE TABLE CONTROL.TSISCOA_Archivo
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TC_Nombre VARCHAR(100),
	TC_Datos VARCHAR(MAX),
	FK_TN_OficinaControl_SISCOA_Archivo INT,
	FOREIGN KEY (FK_TN_OficinaControl_SISCOA_Archivo) REFERENCES [CONTROL].[TSISCOA_OficinaControl](ID)
)
