USE SISCOA


DROP TABLE [CONTROL].[TSISCOA_Archivo]
DROP TABLE [CONTROL].[TSISCOA_OficinaControl]
DROP TABLE [SISTEMA].[TSISCOA_Error]
DROP TABLE [SISTEMA].[TSISCOA_Actividad]
DROP TABLE [USUARIO].[TSISCOA_Usuario]
DROP TABLE [USUARIO].[TSISCOA_RolPermiso]
DROP TABLE [USUARIO].[TSISCOA_Rol]
DROP TABLE [USUARIO].[TSISCOA_Permiso]
DROP TABLE [OFICINA].[TSISCOA_Oficina]
DROP TABLE [CONTROL].[TSISCOA_Control]
DROP TABLE [CONTROL].[TSISCOA_Periodo]
DROP TABLE [CONTROL].[TSISCOA_Estado]
