//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSISCOA_Oficina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSISCOA_Oficina()
        {
            this.TSISCOA_OficinaControl = new HashSet<TSISCOA_OficinaControl>();
            this.TSISCOA_Usuario = new HashSet<TSISCOA_Usuario>();
        }
    
        public int PK_SISCOA_Oficina { get; set; }
        public string TC_CodigoOficina { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_Institucion { get; set; }
        public bool TB_EstadoActividad { get; set; }
        public Nullable<bool> TB_EstaActivo { get; set; }
        public Nullable<bool> TB_EstaBorrado { get; set; }
        public string TC_UltimaModificacion { get; set; }
        public Nullable<System.DateTime> TF_UltimaFechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSISCOA_OficinaControl> TSISCOA_OficinaControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSISCOA_Usuario> TSISCOA_Usuario { get; set; }
    }
}
