//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSISCOA_OficinaControl
    {
        public int PK_TSISCOA_OficinaControl { get; set; }
        public int FK_SISCOA_CONTROL_SISCOA_OficinaControl { get; set; }
        public int FK_SISCOA_OFICINA_SISCOA_OficinaControl { get; set; }
        public Nullable<bool> TB_EstaActivo { get; set; }
        public Nullable<bool> TB_EstaBorrado { get; set; }
        public string TC_UltimaModificacion { get; set; }
        public Nullable<System.DateTime> TF_UltimaFechaModificacion { get; set; }
    
        public virtual TSISCOA_Control TSISCOA_Control { get; set; }
        public virtual TSISCOA_Oficina TSISCOA_Oficina { get; set; }
    }
}
