//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSISCOA_Control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSISCOA_Control()
        {
            this.TSISCOA_OficinaControl = new HashSet<TSISCOA_OficinaControl>();
        }
    
        public int PK_SISCOA_Control { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_DescriptionDocumentacionEvidencia { get; set; }
        public Nullable<int> FK_TN_Estado { get; set; }
        public Nullable<int> FK_TN_Periodo { get; set; }
        public bool TB_NotificacionCorreoAColaborador { get; set; }
        public Nullable<bool> TB_EstaActivo { get; set; }
        public Nullable<bool> TB_EstaBorrado { get; set; }
        public string TC_UltimaModificacion { get; set; }
        public Nullable<System.DateTime> TF_UltimaFechaModificacion { get; set; }
    
        public virtual TSISCOA_Estado TSISCOA_Estado { get; set; }
        public virtual TSISCOA_Periodo TSISCOA_Periodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSISCOA_OficinaControl> TSISCOA_OficinaControl { get; set; }
    }
}
