//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSISCOA_Usuario
    {
        public int PK_SISCOA_Usuario { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_PrimerApellido { get; set; }
        public string TC_SegundoApellido { get; set; }
        public byte[] TV_Contrasenna { get; set; }
        public string TC_Correo { get; set; }
        public int FK_SISCOA_Oficina_SISCOA_Usuario { get; set; }
        public int FK_SISCOA_Rol_SISCOA_Usuario { get; set; }
        public Nullable<bool> TB_EstaActivo { get; set; }
        public Nullable<bool> TB_EstaBorrado { get; set; }
        public string TC_UltimaModificacion { get; set; }
        public Nullable<System.DateTime> TF_UltimaFechaModificacion { get; set; }
    
        public virtual TSISCOA_Oficina TSISCOA_Oficina { get; set; }
        public virtual TSISCOA_Rol TSISCOA_Rol { get; set; }
    }
}
